# Generated by Django 5.0.3 on 2024-04-03 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        choices=[
                            ("Cardiology", "Cardiology"),
                            ("Neurology", "Neurology"),
                            ("Dermatology", "Dermatology"),
                            ("Orthopedics", "Orthopedics"),
                            ("Ophthalmology", "Ophthalmology"),
                            ("Pediatrics", "Pediatrics"),
                            ("Oncology", "Oncology"),
                            ("Gynecology", "Gynecology"),
                            ("Urology", "Urology"),
                            ("Endocrinology", "Endocrinology"),
                            ("Gastroenterology", "Gastroenterology"),
                            ("Hematology", "Hematology"),
                            ("Nephrology", "Nephrology"),
                            ("Pulmonology", "Pulmonology"),
                            ("Rheumatology", "Rheumatology"),
                            ("Allergy and Immunology", "Allergy and Immunology"),
                            ("Anesthesiology", "Anesthesiology"),
                            ("Diagnostic Radiology", "Diagnostic Radiology"),
                            ("Emergency Medicine", "Emergency Medicine"),
                            ("Family Medicine", "Family Medicine"),
                            ("Internal Medicine", "Internal Medicine"),
                            ("Medical Genetics", "Medical Genetics"),
                            ("Nuclear Medicine", "Nuclear Medicine"),
                            ("Obstetrics and Gynecology", "Obstetrics and Gynecology"),
                            ("Pathology", "Pathology"),
                            (
                                "Physical Medicine and Rehabilitation",
                                "Physical Medicine and Rehabilitation",
                            ),
                            ("Preventive Medicine", "Preventive Medicine"),
                            ("Psychiatry", "Psychiatry"),
                            ("Radiation Oncology", "Radiation Oncology"),
                            ("Surgery", "Surgery"),
                            ("Thoracic Surgery", "Thoracic Surgery"),
                            ("Urology", "Urology"),
                            ("Vascular Surgery", "Vascular Surgery"),
                        ],
                        default="Cardiology",
                        max_length=200,
                    ),
                ),
                (
                    "qualification_certificate",
                    models.ImageField(upload_to="doctor_certificates/"),
                ),
                ("experiance", models.PositiveSmallIntegerField()),
                ("resume", models.ImageField(upload_to="doctor_resumes/")),
                ("admin_approved", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
