# Generated by Django 5.0.3 on 2024-04-15 13:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="doctorprofile",
            old_name="user",
            new_name="doctor",
        ),
    ]
