# Generated by Django 5.0.3 on 2024-04-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctorprofile",
            name="qualification_certificate",
            field=models.ImageField(upload_to="accounts/doctor_certificates/"),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="resume",
            field=models.ImageField(upload_to="accounts/doctor_resumes/"),
        ),
    ]
