# Generated by Django 5.0.3 on 2024-04-15 13:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_rename_user_doctorprofile_doctor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="doctorprofile",
            old_name="doctor",
            new_name="user",
        ),
    ]
