# Generated by Django 5.0.3 on 2024-05-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_rename_doctor_doctorprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctorprofile",
            name="specialization",
            field=models.CharField(
                choices=[
                    ("Dermatology", "Dermatology"),
                    ("Allergy and Immunology", "Allergy and Immunology"),
                    ("Gastroenterology", "Gastroenterology"),
                    ("Hepatology", "Hepatology"),
                    ("Pharmacology", "Pharmacology"),
                    ("Pulmonology", "Pulmonology"),
                    ("Cardiology", "Cardiology"),
                    ("Endocrinology", "Endocrinology"),
                    ("Neurology", "Neurology"),
                    ("Orthopedics", "Orthopedics"),
                    ("Internal Medicine", "Internal Medicine"),
                    ("Vascular Medicine", "Vascular Medicine"),
                    ("Rheumatology", "Rheumatology"),
                    ("Urology", "Urology"),
                    ("Physician", "Physician"),
                    ("Pediatrician", "Pediatrician"),
                    ("Gynecology", "Gynecology"),
                    ("Ophthalmology", "Ophthalmology"),
                    ("Otolaryngology", "Otolaryngology"),
                    ("General Surgery", "General Surgery"),
                    ("Oncology", "Oncology"),
                ],
                default="Cardiology",
                max_length=200,
            ),
        ),
    ]
