# Generated by Django 5.0.3 on 2024-05-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_doctorprofile_specialization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctorprofile",
            name="photo",
            field=models.ImageField(
                default="accounts/doctor_profile_photo/profile_photo_default.jpg",
                upload_to="accounts/doctor_profile_photo/",
            ),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="qualification_certificate",
            field=models.FileField(
                default="accounts/doctor_certificates/Qualification_certificate_Ju9LGcp.docx",
                upload_to="accounts/doctor_certificates/",
            ),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="resume",
            field=models.FileField(
                default="accounts/doctor_resumes/resume_bhBPuNm.docx",
                upload_to="accounts/doctor_resumes/",
            ),
        ),
    ]
