# Generated by Django 5.0.3 on 2024-05-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_doctorprofile_photo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctorprofile",
            name="photo",
            field=models.ImageField(upload_to="accounts/doctor_profile_photo/"),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="qualification_certificate",
            field=models.FileField(upload_to="accounts/doctor_certificates/"),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="resume",
            field=models.FileField(upload_to="accounts/doctor_resumes/"),
        ),
    ]
