# Generated by Django 5.0.3 on 2024-04-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0003_clinicdetails_consultation_fee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinicdetails",
            name="consultation_fee",
            field=models.PositiveIntegerField(),
        ),
    ]
