# Generated by Django 5.0.3 on 2024-04-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0004_alter_clinicdetails_consultation_fee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctoroffdays",
            name="date",
            field=models.DateField(unique=True),
        ),
    ]
