# Generated by Django 5.0.3 on 2024-05-02 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_rename_doctor_doctorprofile_user"),
        ("doctor", "0005_alter_doctoroffdays_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorPredictedDisease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symptoms", models.CharField(max_length=2000)),
                ("model", models.CharField(max_length=100)),
                ("disease", models.CharField(max_length=500)),
                ("date", models.DateField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.doctorprofile",
                    ),
                ),
            ],
        ),
    ]
