# Generated by Django 5.0.3 on 2024-04-12 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(upload_to="patient/patient_profile_photo/"),
                ),
                ("address", models.TextField(max_length=600)),
                ("age", models.PositiveIntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "male"),
                            ("female", "female"),
                            ("others", "others"),
                        ],
                        default="male",
                        max_length=50,
                    ),
                ),
                ("height", models.PositiveIntegerField()),
                ("weight", models.PositiveIntegerField()),
                (
                    "previous_illness",
                    models.TextField(blank=True, max_length=800, null=True),
                ),
                (
                    "chronic_diseases",
                    models.TextField(blank=True, max_length=800, null=True),
                ),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
