# Generated by Django 5.0.3 on 2024-04-20 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0002_alter_patientprofile_patient"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientPredictedDisease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symptoms", models.CharField(max_length=2000)),
                ("model", models.CharField(max_length=100)),
                ("disease", models.CharField(max_length=500)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.patientprofile",
                    ),
                ),
            ],
        ),
    ]
