# Generated by Django 5.0.3 on 2024-04-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0003_patientpredicteddisease"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientpredicteddisease",
            name="date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
