# Generated by Django 5.0.3 on 2024-04-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0004_patientpredicteddisease_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientpredicteddisease",
            name="date",
            field=models.DateField(auto_now=True),
        ),
    ]
