# Generated by Django 5.0.3 on 2024-04-21 17:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_rename_doctor_doctorprofile_user"),
        ("patient", "0005_alter_patientpredicteddisease_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientBookedAppointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_id", models.CharField(max_length=500, unique=True)),
                (
                    "appointment_type",
                    models.PositiveIntegerField(choices=[(1, "CLINIC"), (2, "ONLINE")]),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("consulting_fee", models.FloatField()),
                (
                    "payment_status",
                    models.PositiveIntegerField(
                        choices=[(1, "SUCCESS"), (2, "FAILURE"), (3, "PENDING")],
                        default=3,
                    ),
                ),
                (
                    "datetime_of_payment",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "razorpay_order_id",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "razorpay_payment_id",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "razorpay_signature",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.doctorprofile",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.patientprofile",
                    ),
                ),
            ],
        ),
    ]
