# Generated by Django 5.0.3 on 2024-04-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0006_patientbookedappointment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientbookedappointment",
            name="consulting_fee",
            field=models.PositiveBigIntegerField(),
        ),
    ]
