# Generated by Django 5.0.3 on 2024-04-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0007_alter_patientbookedappointment_consulting_fee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientbookedappointment",
            name="time",
            field=models.CharField(max_length=100),
        ),
    ]
