# Generated by Django 5.0.3 on 2024-04-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0008_alter_patientbookedappointment_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientbookedappointment",
            name="booking_id",
            field=models.CharField(max_length=500),
        ),
    ]
