# Generated by Django 5.0.3 on 2024-04-22 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0009_alter_patientbookedappointment_booking_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientbookedappointment",
            name="datetime_of_payment",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 23, 1, 33, 44, 298394)
            ),
        ),
    ]
