# Generated by Django 5.0.3 on 2024-04-22 21:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0010_alter_patientbookedappointment_datetime_of_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientbookedappointment",
            name="datetime_of_payment",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
