# Generated by Django 5.0.3 on 2024-04-29 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_rename_doctor_doctorprofile_user"),
        ("patient", "0011_alter_patientbookedappointment_datetime_of_payment"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnlineConsultationPassKeys",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pass_key", models.CharField(max_length=100)),
                (
                    "booking_instance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.patientbookedappointment",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.doctorprofile",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.patientprofile",
                    ),
                ),
            ],
        ),
    ]
